const FEATURE_IMAGES = {
  liberty: "https://images.unsplash.com/photo-1546436836-07a91091f160?auto=format&fit=crop&w=900&q=80",
  hollywood: "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?auto=format&fit=crop&w=900&q=80",
  sphere: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
  goldenGate: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=900&q=80",
  mountains: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80",
  capitol: "https://images.unsplash.com/photo-1514924013411-cbf25faa35bb?auto=format&fit=crop&w=900&q=80",
  skyline: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=900&q=80",
  beach: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
  harbor: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80",
  forest: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80",
  arch: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=900&q=80",
  canyon: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80",
  desert: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=900&q=80",
  lighthouse: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
  bridge: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=900&q=80",
  nashville: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=900&q=80",
  seattle: "https://images.unsplash.com/photo-1502175353174-a7a70e73b362?auto=format&fit=crop&w=900&q=80",
  philly: "https://images.unsplash.com/photo-1569761316261-9a8696fa2ca3?auto=format&fit=crop&w=900&q=80",
  boston: "https://images.unsplash.com/photo-1501973801540-537f08ccae7b?auto=format&fit=crop&w=900&q=80",
  chicago: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80",
};

const STATE_LANDMARKS = [
  { state: "Alabama", landmark: "Civil Rights Memorial", pageTitle: "Civil_Rights_Memorial", image: FEATURE_IMAGES.skyline },
  { state: "Alaska", landmark: "Denali", pageTitle: "Denali", image: FEATURE_IMAGES.mountains },
  { state: "Arizona", landmark: "Horseshoe Bend", pageTitle: "Horseshoe_Bend_(Arizona)", image: FEATURE_IMAGES.canyon },
  { state: "Arkansas", landmark: "Hot Springs Bathhouse Row", pageTitle: "Bathhouse_Row", image: FEATURE_IMAGES.capitol },
  { state: "California", landmark: "Hollywood Sign", pageTitle: "Hollywood_Sign", image: FEATURE_IMAGES.hollywood },
  { state: "Colorado", landmark: "Maroon Bells", pageTitle: "Maroon_Bells", image: FEATURE_IMAGES.mountains },
  { state: "Connecticut", landmark: "Mystic Seaport", pageTitle: "Mystic_Seaport", image: FEATURE_IMAGES.harbor },
  { state: "Delaware", landmark: "Rehoboth Boardwalk", pageTitle: "Rehoboth_Beach,_Delaware", image: FEATURE_IMAGES.beach },
  { state: "Florida", landmark: "South Beach", pageTitle: "South_Beach", image: FEATURE_IMAGES.beach },
  { state: "Georgia", landmark: "Savannah Historic District", pageTitle: "Historic_districts_of_Savannah,_Georgia", image: FEATURE_IMAGES.harbor },
  { state: "Hawaii", landmark: "Diamond Head", pageTitle: "Diamond_Head,_Hawaii", image: FEATURE_IMAGES.beach },
  { state: "Idaho", landmark: "Shoshone Falls", pageTitle: "Shoshone_Falls", image: FEATURE_IMAGES.forest },
  { state: "Illinois", landmark: "Cloud Gate", pageTitle: "Cloud_Gate", image: FEATURE_IMAGES.chicago },
  { state: "Indiana", landmark: "Soldiers and Sailors Monument", pageTitle: "Indiana_Soldiers'_and_Sailors'_Monument", image: FEATURE_IMAGES.capitol },
  { state: "Iowa", landmark: "Iowa State Capitol", pageTitle: "Iowa_State_Capitol", image: FEATURE_IMAGES.capitol },
  { state: "Kansas", landmark: "Keeper of the Plains", pageTitle: "Keeper_of_the_Plains", image: FEATURE_IMAGES.bridge },
  { state: "Kentucky", landmark: "Churchill Downs", pageTitle: "Churchill_Downs", image: FEATURE_IMAGES.forest },
  { state: "Louisiana", landmark: "French Quarter", pageTitle: "French_Quarter", image: FEATURE_IMAGES.harbor },
  { state: "Maine", landmark: "Portland Head Light", pageTitle: "Portland_Head_Light", image: FEATURE_IMAGES.lighthouse },
  { state: "Maryland", landmark: "Inner Harbor", pageTitle: "Inner_Harbor", image: FEATURE_IMAGES.harbor },
  { state: "Massachusetts", landmark: "Beacon Hill", pageTitle: "Beacon_Hill,_Boston", image: FEATURE_IMAGES.boston },
  { state: "Michigan", landmark: "Mackinac Bridge", pageTitle: "Mackinac_Bridge", image: FEATURE_IMAGES.bridge },
  { state: "Minnesota", landmark: "Stone Arch Bridge", pageTitle: "Stone_Arch_Bridge", image: FEATURE_IMAGES.bridge },
  { state: "Mississippi", landmark: "Biloxi Lighthouse", pageTitle: "Biloxi_Lighthouse", image: FEATURE_IMAGES.lighthouse },
  { state: "Missouri", landmark: "Gateway Arch", pageTitle: "Gateway_Arch", image: FEATURE_IMAGES.arch },
  { state: "Montana", landmark: "Glacier National Park", pageTitle: "Glacier_National_Park_(U.S.)", image: FEATURE_IMAGES.mountains },
  { state: "Nebraska", landmark: "Nebraska State Capitol", pageTitle: "Nebraska_State_Capitol", image: FEATURE_IMAGES.capitol },
  { state: "Nevada", landmark: "Las Vegas Sphere", pageTitle: "Sphere_(venue)", image: FEATURE_IMAGES.sphere },
  { state: "New Hampshire", landmark: "Mount Washington", pageTitle: "Mount_Washington", image: FEATURE_IMAGES.mountains },
  { state: "New Jersey", landmark: "Cape May", pageTitle: "Cape_May,_New_Jersey", image: FEATURE_IMAGES.beach },
  { state: "New Mexico", landmark: "Santa Fe Plaza", pageTitle: "Santa_Fe_Plaza", image: FEATURE_IMAGES.desert },
  { state: "New York", landmark: "Statue of Liberty", pageTitle: "Statue_of_Liberty", image: FEATURE_IMAGES.liberty },
  { state: "North Carolina", landmark: "Biltmore Estate", pageTitle: "Biltmore_Estate", image: FEATURE_IMAGES.forest },
  { state: "North Dakota", landmark: "Theodore Roosevelt Park", pageTitle: "Theodore_Roosevelt_National_Park", image: FEATURE_IMAGES.canyon },
  { state: "Ohio", landmark: "Rock & Roll Hall", pageTitle: "Rock_and_Roll_Hall_of_Fame", image: FEATURE_IMAGES.harbor },
  { state: "Oklahoma", landmark: "SkyDance Bridge", pageTitle: "Skydance_Bridge", image: FEATURE_IMAGES.bridge },
  { state: "Oregon", landmark: "Haystack Rock", pageTitle: "Haystack_Rock", image: FEATURE_IMAGES.beach },
  { state: "Pennsylvania", landmark: "Liberty Bell District", pageTitle: "Liberty_Bell", image: FEATURE_IMAGES.philly },
  { state: "Rhode Island", landmark: "The Breakers", pageTitle: "The_Breakers", image: FEATURE_IMAGES.harbor },
  { state: "South Carolina", landmark: "Rainbow Row", pageTitle: "Rainbow_Row", image: FEATURE_IMAGES.harbor },
  { state: "South Dakota", landmark: "Mount Rushmore", pageTitle: "Mount_Rushmore", image: FEATURE_IMAGES.canyon },
  { state: "Tennessee", landmark: "Broadway Nashville", pageTitle: "Broadway_(Nashville,_Tennessee)", image: FEATURE_IMAGES.nashville },
  { state: "Texas", landmark: "Austin Skyline", pageTitle: "Austin,_Texas", image: FEATURE_IMAGES.skyline },
  { state: "Utah", landmark: "Delicate Arch", pageTitle: "Delicate_Arch", image: FEATURE_IMAGES.desert },
  { state: "Vermont", landmark: "Stowe Village", pageTitle: "Stowe,_Vermont", image: FEATURE_IMAGES.forest },
  { state: "Virginia", landmark: "Monticello", pageTitle: "Monticello", image: FEATURE_IMAGES.capitol },
  { state: "Washington", landmark: "Space Needle", pageTitle: "Space_Needle", image: FEATURE_IMAGES.seattle },
  { state: "West Virginia", landmark: "New River Gorge Bridge", pageTitle: "New_River_Gorge_Bridge", image: FEATURE_IMAGES.bridge },
  { state: "Wisconsin", landmark: "Milwaukee Art Museum", pageTitle: "Milwaukee_Art_Museum", image: FEATURE_IMAGES.harbor },
  { state: "Wyoming", landmark: "Grand Teton", pageTitle: "Grand_Teton", image: FEATURE_IMAGES.mountains },
];

export const landingWallItems = STATE_LANDMARKS.map((item, index) => ({
  id: `${item.state}-${index}`,
  ...item,
  column: index % 5,
}));

export const landingProductStats = {
  cityCount: 1200,
  zipCount: 32000,
};
